// Proto-generated types for the kubesavings.v1 package.
// build.rs compiles proto/kubesavings.proto automatically on `cargo build`.
// DO NOT edit this file manually — change proto/kubesavings.proto instead.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/kubesavings.v1.rs"));
}

pub use proto::{AgentSnapshot, NamespaceMetrics, NodePool, SnapshotResponse, WorkloadMetrics};
